apiVersion: appprotect.f5.com/v1beta1
kind: APUserSig
metadata:
  name: banana
spec:
  signatures:
  - accuracy: medium
    attackType:
      name: Brute Force Attack
    description: Medium accuracy user defined signature with tag (Fruits)
    name: Banana_medium_acc
    risk: medium
    rule: content:"banana"; nocase;
    signatureType: request
    systems:
    - name: Microsoft Windows
    - name: Unix/Linux
  tag: Fruits-prime
