apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: juice-shop-vs
spec:
  host: owasp-juiceshop.example.com
  policies:
  - name: waf-policy-prime
  tls:
    secret: bookinfo-secret
  upstreams:
  - name: owasp-juice-shop
    service: juice-shop
    port: 8000
  routes:
  - path: /
    action:
      pass: owasp-juice-shop
