apiVersion: k8s.nginx.org/v1
kind: Policy
metadata:
  name: waf-policy-prime
spec:
  waf:
    enable: true
    apPolicy: "default/dataguard-alarm-prime"
    securityLog:
      enable: true
      apLogConf: "default/logconf-prime"
      logDest: "syslog:server=syslog-svc.default:514"
